name: servant-crud-elm
version: 0.1.0.0
github: 'githubuser/servant-crud-elm'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2019 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/servant-crud-elm#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - basement
    - bytestring
    - conduit
    - directory
    - elm-bridge
    - monad-logger
    - mtl
    - persistent
    - persistent-sqlite
    - persistent-template
    - resource-pool
    - safe-exceptions
    - servant-crud
    - servant-elm
    - servant-server
    - string-conversions
    - stm
    - time

executables:
  servant-crud-elm-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - servant-crud-elm
      - warp

tests:
  servant-crud-elm-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - servant-crud-elm
